

--TABLA PROVEEDORES

CREATE TABLE PROVEEDORES (
[ID_PROVEEDOR] [INT] IDENTITY (1,1) NOT NULL PRIMARY KEY,
[RNC] [INT] NOT NULL,
[NOMBRE] [VARCHAR] (25) NOT NULL,
[TELEFONO] [VARCHAR] (13) NOT NULL,
[DIRECCION] [VARCHAR] (35) NULL,
[EMAIL] [VARCHAR] (35) NULL,
[SUMINISTRO] [VARCHAR](50) NOT NULL

)


--TABLA CLIENTES

    CREATE TABLE CLIENTES (
	[ID_CLIENTE] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOMBRE] [VARCHAR](25) NOT NULL,
	[APELLIDO] [VARCHAR](25) NOT NULL,
	[CEDULA] [VARCHAR](13) NOT NULL,
	[EMAIL] [VARCHAR](35) NULL,
	[TELEFONO] [VARCHAR](12) NOT NULL,
	[SEGURO] [VARCHAR] (15) NULL
	

)
--TABLA USUARIOS

    CREATE TABLE USUARIOS (
	[ID_USUARIO] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOMBRE] [VARCHAR](25) NOT NULL,
	[CONTRASENA] [VARCHAR](50) NOT NULL,
	[CARGO] [VARCHAR] (15) NOT NULL,
	[PRIVILEGIOS] [VARCHAR] (15) NOT NULL
	
)

insert into USUARIOS(NOMBRE,CONTRASENA,CARGO,PRIVILEGIOS) VALUES ('usuario','1234','administrador','Administrador')
            

--TABLA INVENTARIO

    CREATE TABLE INVENTARIO (
    [ID_PRODUCTO] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ID_PROVEEDOR] [INT] FOREIGN KEY REFERENCES PROVEEDORES(ID_PROVEEDOR),
	[PRODUCTO] [VARCHAR](25) NOT NULL,
	[PRECIO] [MONEY] NOT NULL,
	[CANTIDAD] [INT] NOT NULL,
	[FECHA_VENCIMIENTO] [DATETIME] NOT NULL,
	[UBICACION] [VARCHAR] (50) NOT NULL,	
	[DESCRIPCION] [VARCHAR] (255) NULL,
	[USUARIO] [VARCHAR] (40) NOT NULL,
	[FECHA_INGRESO] [DATETIME] NOT NULL
	
)


